// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/wujianling/moringstaradmin/internal/mods"
	"github.com/wujianling/moringstaradmin/internal/mods/artivitycenter"
	api8 "github.com/wujianling/moringstaradmin/internal/mods/artivitycenter/api"
	biz8 "github.com/wujianling/moringstaradmin/internal/mods/artivitycenter/biz"
	dal8 "github.com/wujianling/moringstaradmin/internal/mods/artivitycenter/dal"
	"github.com/wujianling/moringstaradmin/internal/mods/commoncenter"
	api4 "github.com/wujianling/moringstaradmin/internal/mods/commoncenter/api"
	biz4 "github.com/wujianling/moringstaradmin/internal/mods/commoncenter/biz"
	dal4 "github.com/wujianling/moringstaradmin/internal/mods/commoncenter/dal"
	"github.com/wujianling/moringstaradmin/internal/mods/customercenter"
	api2 "github.com/wujianling/moringstaradmin/internal/mods/customercenter/api"
	biz2 "github.com/wujianling/moringstaradmin/internal/mods/customercenter/biz"
	dal2 "github.com/wujianling/moringstaradmin/internal/mods/customercenter/dal"
	"github.com/wujianling/moringstaradmin/internal/mods/ordercenter"
	api3 "github.com/wujianling/moringstaradmin/internal/mods/ordercenter/api"
	biz3 "github.com/wujianling/moringstaradmin/internal/mods/ordercenter/biz"
	dal3 "github.com/wujianling/moringstaradmin/internal/mods/ordercenter/dal"
	"github.com/wujianling/moringstaradmin/internal/mods/paycenter"
	api7 "github.com/wujianling/moringstaradmin/internal/mods/paycenter/api"
	biz7 "github.com/wujianling/moringstaradmin/internal/mods/paycenter/biz"
	dal7 "github.com/wujianling/moringstaradmin/internal/mods/paycenter/dal"
	"github.com/wujianling/moringstaradmin/internal/mods/productcenter"
	api6 "github.com/wujianling/moringstaradmin/internal/mods/productcenter/api"
	biz6 "github.com/wujianling/moringstaradmin/internal/mods/productcenter/biz"
	dal6 "github.com/wujianling/moringstaradmin/internal/mods/productcenter/dal"
	"github.com/wujianling/moringstaradmin/internal/mods/rbac"
	"github.com/wujianling/moringstaradmin/internal/mods/rbac/api"
	"github.com/wujianling/moringstaradmin/internal/mods/rbac/biz"
	"github.com/wujianling/moringstaradmin/internal/mods/rbac/dal"
	"github.com/wujianling/moringstaradmin/internal/mods/shopcenter"
	api5 "github.com/wujianling/moringstaradmin/internal/mods/shopcenter/api"
	biz5 "github.com/wujianling/moringstaradmin/internal/mods/shopcenter/biz"
	dal5 "github.com/wujianling/moringstaradmin/internal/mods/shopcenter/dal"
	"github.com/wujianling/moringstaradmin/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCacher(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup3, err := InitAuth(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	trans := &util.Trans{
		DB: db,
	}
	menu := &dal.Menu{
		DB: db,
	}
	menuResource := &dal.MenuResource{
		DB: db,
	}
	roleMenu := &dal.RoleMenu{
		DB: db,
	}
	bizMenu := &biz.Menu{
		Cache:           cacher,
		Trans:           trans,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleMenuDAL:     roleMenu,
	}
	apiMenu := &api.Menu{
		MenuBIZ: bizMenu,
	}
	role := &dal.Role{
		DB: db,
	}
	userRole := &dal.UserRole{
		DB: db,
	}
	bizRole := &biz.Role{
		Cache:       cacher,
		Trans:       trans,
		RoleDAL:     role,
		RoleMenuDAL: roleMenu,
		UserRoleDAL: userRole,
	}
	apiRole := &api.Role{
		RoleBIZ: bizRole,
	}
	user := &dal.User{
		DB: db,
	}
	bizUser := &biz.User{
		Cache:       cacher,
		Trans:       trans,
		UserDAL:     user,
		UserRoleDAL: userRole,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	login := &biz.Login{
		Cache:       cacher,
		Auth:        auther,
		UserDAL:     user,
		UserRoleDAL: userRole,
		MenuDAL:     menu,
		UserBIZ:     bizUser,
	}
	apiLogin := &api.Login{
		LoginBIZ: login,
	}
	logger := &dal.Logger{
		DB: db,
	}
	bizLogger := &biz.Logger{
		LoggerDAL: logger,
	}
	apiLogger := &api.Logger{
		LoggerBIZ: bizLogger,
	}
	casbinx := &rbac.Casbinx{
		Cache:           cacher,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleDAL:         role,
	}
	rbacRBAC := &rbac.RBAC{
		DB:        db,
		MenuAPI:   apiMenu,
		RoleAPI:   apiRole,
		UserAPI:   apiUser,
		LoginAPI:  apiLogin,
		LoggerAPI: apiLogger,
		Casbinx:   casbinx,
	}
	customer := &dal2.Customer{
		DB: db,
	}
	bizCustomer := &biz2.Customer{
		Trans:       trans,
		CustomerDAL: customer,
	}
	apiCustomer := &api2.Customer{
		CustomerBIZ: bizCustomer,
	}
	customerCenter := &customercenter.CustomerCenter{
		DB:          db,
		CustomerAPI: apiCustomer,
	}
	orders := &dal3.Orders{
		DB: db,
	}
	bizOrders := &biz3.Orders{
		Trans:     trans,
		OrdersDAL: orders,
	}
	apiOrders := &api3.Orders{
		OrdersBIZ: bizOrders,
	}
	orderCenter := &ordercenter.OrderCenter{
		DB:        db,
		OrdersAPI: apiOrders,
	}
	common := &dal4.Common{
		DB: db,
	}
	bizCommon := &biz4.Common{
		Trans:     trans,
		CommonDAL: common,
	}
	apiCommon := &api4.Common{
		CommonBIZ: bizCommon,
	}
	commonCenter := &commoncenter.CommonCenter{
		DB:        db,
		CommonAPI: apiCommon,
	}
	shop := &dal5.Shop{
		DB: db,
	}
	bizShop := &biz5.Shop{
		Trans:   trans,
		ShopDAL: shop,
	}
	apiShop := &api5.Shop{
		ShopBIZ: bizShop,
	}
	shopCenter := &shopcenter.ShopCenter{
		DB:      db,
		ShopAPI: apiShop,
	}
	product := &dal6.Product{
		DB: db,
	}
	bizProduct := &biz6.Product{
		Trans:      trans,
		ProductDAL: product,
	}
	apiProduct := &api6.Product{
		ProductBIZ: bizProduct,
	}
	productCenter := &productcenter.ProductCenter{
		DB:         db,
		ProductAPI: apiProduct,
	}
	balance := &dal7.Balance{
		DB: db,
	}
	bizBalance := &biz7.Balance{
		Trans:      trans,
		BalanceDAL: balance,
	}
	apiBalance := &api7.Balance{
		BalanceBIZ: bizBalance,
	}
	payCenter := &paycenter.PayCenter{
		DB:         db,
		BalanceAPI: apiBalance,
	}
	artivity := &dal8.Artivity{
		DB: db,
	}
	bizArtivity := &biz8.Artivity{
		Trans:       trans,
		ArtivityDAL: artivity,
	}
	apiArtivity := &api8.Artivity{
		ArtivityBIZ: bizArtivity,
	}
	artivityCenter := &artivitycenter.ArtivityCenter{
		DB:          db,
		ArtivityAPI: apiArtivity,
	}
	modsMods := &mods.Mods{
		RBAC:           rbacRBAC,
		CustomerCenter: customerCenter,
		OrderCenter:    orderCenter,
		CommonCenter:   commonCenter,
		ShopCenter:     shopCenter,
		ProductCenter:  productCenter,
		PayCenter:      payCenter,
		ArtivityCenter: artivityCenter,
	}
	injector := &Injector{
		DB:    db,
		Cache: cacher,
		Auth:  auther,
		M:     modsMods,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
