// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: authCenter.proto

package server

import (
	"context"

	"MoringStarService/authCenter/authCenter"
	"MoringStarService/authCenter/internal/logic"
	"MoringStarService/authCenter/internal/svc"
)

type AuthCenterServer struct {
	svcCtx *svc.ServiceContext
	authCenter.UnimplementedAuthCenterServer
}

func NewAuthCenterServer(svcCtx *svc.ServiceContext) *AuthCenterServer {
	return &AuthCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthCenterServer) Ping(ctx context.Context, in *authCenter.Request) (*authCenter.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
