// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: authCenter.proto

package authCenter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthCenter_Ping_FullMethodName = "/authCenter.AuthCenter/Ping"
)

// AuthCenterClient is the client API for AuthCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthCenterClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type authCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthCenterClient(cc grpc.ClientConnInterface) AuthCenterClient {
	return &authCenterClient{cc}
}

func (c *authCenterClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, AuthCenter_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthCenterServer is the server API for AuthCenter service.
// All implementations must embed UnimplementedAuthCenterServer
// for forward compatibility.
type AuthCenterServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAuthCenterServer()
}

// UnimplementedAuthCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthCenterServer struct{}

func (UnimplementedAuthCenterServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAuthCenterServer) mustEmbedUnimplementedAuthCenterServer() {}
func (UnimplementedAuthCenterServer) testEmbeddedByValue()                    {}

// UnsafeAuthCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthCenterServer will
// result in compilation errors.
type UnsafeAuthCenterServer interface {
	mustEmbedUnimplementedAuthCenterServer()
}

func RegisterAuthCenterServer(s grpc.ServiceRegistrar, srv AuthCenterServer) {
	// If the following call pancis, it indicates UnimplementedAuthCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthCenter_ServiceDesc, srv)
}

func _AuthCenter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCenterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthCenter_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCenterServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthCenter_ServiceDesc is the grpc.ServiceDesc for AuthCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authCenter.AuthCenter",
	HandlerType: (*AuthCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AuthCenter_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authCenter.proto",
}
