// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: authCenter.proto

package authCenterClient

import (
	"context"

	"MoringStarService/authCenter/authCenter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = authCenter.Request
	Response = authCenter.Response

	AuthCenter interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAuthCenter struct {
		cli zrpc.Client
	}
)

func NewAuthCenter(cli zrpc.Client) AuthCenter {
	return &defaultAuthCenter{
		cli: cli,
	}
}

func (m *defaultAuthCenter) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := authCenter.NewAuthCenterClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
